/* The narrator: a data-to-text generator over a vitai read model.
 *
 * Not a language model, and the choice is argued in docs/prior-art.md rather
 * than assumed. The short version: a sub-10 MB model that emits fluent English
 * is available off the shelf (TinyStories, llama2.c), and fluent English about
 * a person's body, generated by a component that cannot know whether it is
 * true, is the most dangerous thing this repository could ship. Weizenbaum
 * established in 1966 that people read fluency as understanding. Nothing since
 * has made that safer.
 *
 * The architecture is the standard NLG pipeline (Reiter and Dale, 2000), and
 * the stages are kept apart on purpose: a reviewer who wants to know whether
 * this thing is honest reads CONTENT DETERMINATION, which is a list of rules
 * over rows, and never has to read a template.
 *
 *   stage 1  content determination  which facts deserve a sentence   RULES
 *   stage 2  document planning      order and grouping               plan()
 *   stage 3  microplanning          aggregation, lexical choice      in-rule
 *   stage 4  surface realisation    plurals, lists, agreement        helpers
 *
 * THE RULE, in full:
 *
 *   The narrator may state what the engine stated, and may state how many
 *   times the engine stated it. It may not derive a new quantity from the
 *   values in the rows.
 *
 * So COUNT(*) is allowed, because that is a property of the query. AVG(kg) is
 * not, because that is a health judgment, and health judgments belong to the
 * engine where they can be tested. Where the engine has already produced text
 * - gates.escalation, verdicts.reason - it is quoted verbatim and never
 * paraphrased, which is the discipline safety.py applies when it emits
 * hardcoded escalation strings rather than letting a model phrase them.
 *
 * Every message carries the SQL that produced it. The UI renders that as a
 * "show the rows" control which runs the query for real. A sentence you cannot
 * trace is a sentence this file is not allowed to emit.
 */
"use strict";

const Narrator = (() => {

  /* ---- stage 4: surface realisation ------------------------------------ */

  const plural = (n, one, many) => (n === 1 ? one : (many || one + "s"));

  // Counts read as prose, not as data. "2 goals are below the floor" is a
  // spreadsheet talking; a measured QUANTITY stays in digits, because "sixty
  // five thousand two hundred and ninety steps" helps nobody.
  const WORDS = ["zero", "one", "two", "three", "four", "five",
                 "six", "seven", "eight", "nine"];
  const count = (n) => (n >= 0 && n < WORDS.length && Number.isInteger(n))
    ? WORDS[n] : num(n);

  function listify(items) {
    if (items.length === 0) return "";
    if (items.length === 1) return items[0];
    return items.slice(0, -1).join(", ") + " and " + items[items.length - 1];
  }

  // Numbers are rendered, never recomputed. The dp argument chooses how much
  // of a stored value to show; it does not round anything into existence.
  const num = (x, dp = 0) =>
    (x === null || x === undefined) ? "" :
      Number(x).toLocaleString("en-GB", { maximumFractionDigits: dp,
                                          minimumFractionDigits: 0 });

  const esc = (s) => String(s).replace(/[&<>]/g,
    c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]));

  const quote = (s) => `<q>${esc(String(s).replace(/\s+/g, " ").trim())}</q>`;

  // A message begins a sentence. Rules interpolate a title or a column name at
  // position zero often enough that leaving this to each rule guarantees one
  // of them forgets.
  const cap = (s) => s.replace(/^(<[^>]+>)*[a-z]/,
    m => m.slice(0, -1) + m.slice(-1).toUpperCase());

  /* Stage 3, lexical choice. A metric is stored as a column name because that
   * is what it is; printing `distance_km` in a sentence tells the reader the
   * developer stopped caring at the database boundary. An unmapped metric
   * falls through as its own name rather than being dropped, so a new metric
   * reads awkwardly instead of vanishing. */
  const UNIT = {
    distance_km: "km", steps: "steps", active_min: "active minutes",
    kg: "kg", kcal_in: "kcal", kcal_out: "kcal", protein_g: "g protein",
    sleep_h: "hours of sleep", rhr: "bpm", external: null,
  };
  const PERIOD = { weekly: "a week", daily: "a day", monthly: "a month" };

  // "13.38 of 30 km a week". Renders only what the row holds; a missing unit
  // or period drops out of the phrase rather than being invented.
  function quantity(counted, target, metric, period) {
    const unit = UNIT[metric] !== undefined ? UNIT[metric] : metric;
    const per = PERIOD[period] || "";
    const tail = [unit, per].filter(Boolean).join(" ");
    const head = (counted === null || counted === undefined)
      ? `a target of ${num(target, 2)}` : `${num(counted, 2)} of ${num(target, 2)}`;
    return tail ? `${head} ${tail}` : head;
  }

  /* ---- stage 1: content determination ---------------------------------- */
  /* Each rule returns zero or more messages. A rule that finds nothing worth
   * saying says nothing: silence is a valid and common output, and a rule that
   * always produces a sentence is a rule that is padding.                   */

  const RULES = [];
  const rule = (id, section, priority, run) =>
    RULES.push({ id, section, priority, run });

  /* An open gate outranks everything. The engine wrote the escalation text;
   * it is reproduced without editing. G68: safety fires unconfigured.       */
  rule("open-gate", "now", 0, (q) => {
    const sql = "SELECT date, slug, restricts, reason, severity, status, " +
                "precondition, escalation FROM gates WHERE status <> 'cleared'";
    return q(sql).map(g => {
      // `reason` already ends with the check and its status, which the next
      // clause states properly. Repeating it reads as a stutter.
      const why = String(g.reason).replace(/\s*-\s*check\s+'[^']*':.*$/, "");
      return {
        tone: "stop",
        text: `<strong>${esc(g.restricts)} work is gated.</strong> ` +
              `The engine recorded ${quote(why)}, severity ` +
              `<code>${esc(g.severity)}</code>, and set one condition: ` +
              `<code>${esc(g.precondition)}</code>, currently ` +
              `<code>${esc(g.status)}</code>. ` +
              `Its words, not mine: ${quote(g.escalation)}`,
        sql,
      };
    });
  });

  /* Goals below a floor. Aggregated into one sentence (stage 3) because three
   * separate sentences of the same shape read as three separate problems.   */
  rule("goal-breach", "goals", 10, (q) => {
    const sql = "SELECT slug, title, polarity, metric, period, progress_pct, " +
                "counted, target, breach FROM goal_progress " +
                "WHERE breach IS NOT NULL ORDER BY progress_pct";
    const rs = q(sql);
    if (!rs.length) return [];
    const parts = rs.map(r =>
      `<em>${esc(r.title)}</em> (${quantity(r.counted, r.target, r.metric, r.period)}, ` +
      `${num(r.progress_pct, 0)} per cent)`);
    return [{
      tone: "watch",
      text: `${rs.length === 1 ? "One goal is" : count(rs.length) + " goals are"} ` +
            `below the ${rs[0].polarity === "floor" ? "floor" : "line"} you set: ` +
            listify(parts) + ". " +
            "That is the engine's arithmetic against the target you declared, " +
            "not a judgment about the week.",
      sql,
    }];
  });

  /* The other side of the same table, and it has to be said in the same
   * breath, or the narrator only ever reports deficits - which is a way of
   * lying by selection while every individual sentence stays true.          */
  rule("goal-holding", "goals", 11, (q) => {
    const sql = "SELECT slug, title, metric, period, achievement_status, " +
                "lifecycle_status, progress_pct, counted, target " +
                "FROM goal_progress WHERE achievement_status = 'sustaining'";
    const rs = q(sql);
    return rs.map(r => ({
      tone: "good",
      text: `<em>${esc(r.title)}</em> is marked <code>sustaining</code>: ` +
            `${quantity(r.counted, r.target, r.metric, r.period)}. ` +
            `The engine closed this one and is still counting it.`,
      sql,
    }));
  });

  /* G83: what someone would be sad to lose is never a number. A goal with no
   * target is not an incomplete goal, and the narrator must not treat it as
   * an omission to be chased.
   *
   * Split by `verification`, because "has no target" fuses two unrelated
   * things and this project does not fuse axes. A goal verified by ATTESTATION
   * has no number because none would mean anything; a goal verified
   * EXTERNALLY has a perfectly good number that lives somewhere this engine
   * cannot see. Reporting them in one sentence would imply the second is as
   * unmeasurable as the first, which is false and would read as this tool
   * declining to look.                                                       */
  rule("goal-attested", "goals", 12, (q) => {
    const sql = "SELECT slug, title, motivator FROM goal_progress " +
                "WHERE target IS NULL AND verification = 'attested'";
    const rs = q(sql);
    if (!rs.length) return [];
    return [{
      tone: "note",
      text: `${count(rs.length)} of your goals ${plural(rs.length, "carries", "carry")} ` +
            `no number and ${plural(rs.length, "is", "are")} true only when you ` +
            `say so: ` + listify(rs.map(r => `<em>${esc(r.title)}</em>`)) + ". " +
            "Nothing here can score " + plural(rs.length, "it", "them") + ", and " +
            "that is not a gap in the record. Some of what a person is training " +
            "for does not reduce to a quantity, and a tool that only recognises " +
            "the measurable ones will quietly talk you out of the rest.",
      sql,
    }];
  });

  rule("goal-external", "goals", 12.5, (q) => {
    const sql = "SELECT slug, title, tracker, event FROM goal_progress " +
                "WHERE target IS NULL AND verification = 'external'";
    const rs = q(sql);
    if (!rs.length) return [];
    const parts = rs.map(r => `<em>${esc(r.title)}</em>` +
      (r.tracker ? ` (${esc(r.tracker)})` : ""));
    return [{
      tone: "note",
      text: `${count(rs.length)} ${plural(rs.length, "goal is", "goals are")} ` +
            `settled somewhere this engine cannot see: ` + listify(parts) + ". " +
            `There is a number, and it is not in here. The engine tracks ` +
            plural(rs.length, "it", "them") + ` without pretending to measure ` +
            plural(rs.length, "it", "them") + `, which is the honest position ` +
            `for a tool holding only its own record.`,
      sql,
    }];
  });

  /* A hard deadline that has passed on a goal nobody has closed. Stated as a
   * fact about the record, with no verdict attached: the engine has not
   * decided this goal failed, and neither has the athlete, and it is not the
   * narrator's business to break the tie.                                    */
  rule("deadline-passed", "goals", 14, (q) => {
    const sql = "SELECT slug, title, deadline, deadline_kind, days_to_deadline, " +
                "lifecycle_status, verification FROM goal_progress " +
                "WHERE days_to_deadline < 0 AND lifecycle_status = 'active'";
    const rs = q(sql);
    return rs.map(r => ({
      tone: "watch",
      text: `<em>${esc(r.title)}</em> passed its ` +
            `${r.deadline_kind === "hard" ? "hard " : ""}deadline of ` +
            `${esc(r.deadline)}, ${num(Math.abs(r.days_to_deadline))} days ago, ` +
            `and is still open. ` +
            (r.verification === "external"
              ? "Nothing has arrived to settle it, which is what a goal held " +
                "outside the record looks like when the result never comes back in."
              : "The engine has not marked it missed and will not do so on its own."),
      sql,
    }));
  });

  /* Two sources disagreed. The independence split is the whole point and the
   * distinction was learned the hard way on this project: two transcriptions
   * of one instrument agreeing tells you the transcription was faithful, and
   * tells you nothing whatever about the measurement.                       */
  rule("conflicts", "record", 20, (q) => {
    const sql = "SELECT date, dataset, field, chosen_source, chosen_value, " +
                "over_source, over_value, independent, reason FROM resolution " +
                "WHERE disagreed = 1 ORDER BY date";
    const rs = q(sql);
    if (!rs.length) return [];
    const indep = rs.filter(r => r.independent).length;
    const fields = [...new Set(rs.map(r => r.field))];
    let text =
      `Two sources disagreed ${count(rs.length)} ${plural(rs.length, "time")}, ` +
      `over ${listify(fields.map(f => `<code>${esc(f)}</code>`))}. ` +
      `The engine picked a winner each time and kept the loser.`;
    if (indep !== rs.length) {
      text += ` ${cap(count(rs.length - indep))} of those ` +
        `${plural(rs.length - indep, "was", "were")} between sources the engine ` +
        `does not consider independent, which is a weaker thing than it looks: ` +
        `when one instrument reaches the record by two paths, agreement checks ` +
        `the copying and not the measurement.`;
    }
    return [{ tone: "note", text, sql }];
  });

  /* Where the numbers came from. 162 of 193 rows arriving by unknown transit
   * is the single most honest thing this database has to say about itself.  */
  rule("provenance", "record", 21, (q) => {
    // The total is asked of the database rather than summed from the group
    // counts here. Adding them up would be a new quantity computed in the
    // client, which is the one thing this file may not do, and the grounding
    // test caught it doing precisely that.
    const sql = "SELECT trust, COUNT(*) AS n, SUM(COUNT(*)) OVER () AS total " +
                "FROM provenance GROUP BY trust ORDER BY n DESC";
    const rs = q(sql);
    if (!rs.length) return [];
    const total = rs[0].total;
    const top = rs[0];
    const parts = rs.map(r => `<code>${esc(r.trust)}</code> ${num(r.n)}`);
    let text = `Provenance across ${num(total)} record-days: ` +
               listify(parts) + ".";
    if (top.trust === "unknown-transit") {
      text += " The largest group is the one where the number arrived and the " +
              "path it took did not. Those values are not wrong; it is their " +
              "custody that is unrecorded, and no amount of charting will " +
              "recover it after the fact.";
    }
    return [{ tone: "note", text, sql }];
  });

  /* G82: the unaccounted period. State that it exists, never ask why. The
   * days a person stops logging are frequently the days worth knowing about,
   * and a tool that demands an explanation is a tool they will stop opening. */
  rule("unlogged", "record", 22, (q) => {
    // One query, not three. The two side queries this used to run produced
    // numbers the "show the rows" control would not have shown, which is the
    // same defect as inventing them.
    const sql = "SELECT COUNT(*) AS logged, MIN(date) AS a, MAX(date) AS b, " +
                "SUM(CASE WHEN coverage IS NULL THEN 1 ELSE 0 END) AS blank, " +
                "SUM(CASE WHEN coverage = 'partial' THEN 1 ELSE 0 END) AS partial " +
                "FROM daily";
    const r = q(sql)[0];
    if (!r || !r.logged) return [];
    const partial = { n: r.partial }, blank = { n: r.blank };
    let text = `The record runs ${esc(r.a)} to ${esc(r.b)}, ` +
               `${num(r.logged)} days.`;
    if (blank && blank.n) {
      text += ` ${cap(count(blank.n))} of them carry no coverage marking at all, ` +
              `which the engine keeps distinct from a day marked empty. ` +
              `Unannotated is not the same as nothing happened.`;
    }
    if (partial && partial.n) {
      text += ` ${cap(count(partial.n))} ${plural(partial.n, "is", "are")} marked <code>partial</code>.`;
    }
    return [{ tone: "note", text, sql }];
  });

  /* Weekly verdicts, counted by outcome. no_data is reported as its own
   * category and never folded into a miss: not measuring is not failing.    */
  rule("verdicts", "record", 23, (q) => {
    const sql = "SELECT verdict, COUNT(*) AS n, SUM(COUNT(*)) OVER () AS total " +
                "FROM verdicts GROUP BY verdict ORDER BY n DESC";
    const rs = q(sql);
    if (!rs.length) return [];
    const by = Object.fromEntries(rs.map(r => [r.verdict, r.n]));
    const total = rs[0].total;
    let text = `Across ${num(total)} weekly checks the engine returned ` +
               listify(rs.map(r => `<code>${esc(r.verdict)}</code> ${num(r.n)}`)) + ".";
    if (by.no_data) {
      text += ` The ${count(by.no_data)} <code>no_data</code> ` +
              `${plural(by.no_data, "week")} ${plural(by.no_data, "is", "are")} ` +
              `not ${plural(by.no_data, "a miss", "misses")}. ` +
              `The engine declines to score a week it cannot see, and refusing ` +
              `to guess is the behaviour, not a shortcoming of it.`;
    }
    return [{ tone: "note", text, sql }];
  });

  /* Claims that were merged. The record changing its mind is a feature and
   * ought to be visible rather than quietly resolved behind the read model. */
  rule("merged", "record", 24, (q) => {
    const sql = "SELECT claim_id, dataset, date, source, merged_into " +
                "FROM claims WHERE merged_into IS NOT NULL";
    const rs = q(sql);
    if (!rs.length) return [];
    return [{
      tone: "note",
      text: `${cap(count(rs.length))} ${plural(rs.length, "claim")} ` +
            `${plural(rs.length, "was", "were")} each superseded by a later one. ` +
            `The originals are still in the log; the read model shows what won, ` +
            `and the log shows that anything was ever in question.`,
      sql,
    }];
  });

  /* Milestones under a target that has since moved. This is G25 made visible:
   * old rows keep validating, so the history of a goal survives its edit.   */
  rule("milestone-history", "goals", 13, (q) => {
    const sql = "SELECT label, COUNT(*) AS n FROM milestones " +
                "GROUP BY label ORDER BY n DESC";
    const rs = q(sql);
    if (rs.length < 2) return [];
    const targets = new Set();
    for (const r of rs) {
      const m = /of (.+)$/.exec(r.label);
      if (m) targets.add(m[1]);
    }
    const steps = [...targets].filter(t => /\d/.test(t));
    if (steps.length < 2) return [];
    return [{
      tone: "note",
      text: `The milestone log names more than one version of the same goal ` +
            `(${listify([...targets].slice(0, 3).map(t => `<em>${esc(t)}</em>`))}` +
            `${targets.size > 3 ? ", and others" : ""}). ` +
            `A goal that was edited did not erase what was true under the old ` +
            `one. Progress recorded against a target you have since raised is ` +
            `still progress that happened.`,
      sql,
    }];
  });

  /* ---- stage 2: document planning -------------------------------------- */

  const SECTIONS = [
    { id: "now",    title: "What needs attention" },
    { id: "goals",  title: "Against what you said you wanted" },
    { id: "record", title: "What the record knows about itself" },
  ];

  function plan(messages) {
    const out = [];
    for (const s of SECTIONS) {
      const mine = messages.filter(m => m.section === s.id)
                           .sort((a, b) => a.priority - b.priority);
      if (mine.length) out.push({ ...s, messages: mine });
    }
    return out;
  }

  /* ---- driver ----------------------------------------------------------- */

  function generate(query) {
    const messages = [];
    for (const r of RULES) {
      let produced;
      try {
        produced = r.run(query) || [];
      } catch (err) {
        /* A rule that throws is a broken rule, and the honest report of a
         * broken rule is not silence. Silence here would be a narrator that
         * shrinks as the schema drifts while continuing to look complete,
         * which is precisely the failure this client exists to refuse.     */
        produced = [{
          tone: "broken",
          text: `The rule <code>${esc(r.id)}</code> could not run against this ` +
                `database: <code>${esc(err && err.message || err)}</code>. ` +
                `Whatever it had to say is missing from what follows.`,
          sql: null,
        }];
      }
      for (const m of produced) {
        messages.push({ ...m, text: cap(m.text), rule: r.id,
                        section: r.section, priority: r.priority });
      }
    }
    return plan(messages);
  }

  return { generate, RULES, _internal: { listify, plural, num } };
})();

if (typeof module !== "undefined" && module.exports) module.exports = Narrator;
