/* The narrator: a data-to-text generator over a vitai read model.
 *
 * Not a language model, and the choice is argued in docs/prior-art.md rather
 * than assumed. The short version: a sub-10 MB model that emits fluent English
 * is available off the shelf (TinyStories, llama2.c), and fluent English about
 * a person's body, generated by a component that cannot know whether it is
 * true, is the most dangerous thing this repository could ship. Weizenbaum
 * established in 1966 that people read fluency as understanding. Nothing since
 * has made that safer.
 *
 * The architecture is the standard NLG pipeline (Reiter and Dale, 2000), and
 * the stages are kept apart on purpose: a reviewer who wants to know whether
 * this thing is honest reads CONTENT DETERMINATION, which is a list of rules
 * over rows, and never has to read a template.
 *
 *   stage 1  content determination  which facts deserve a sentence   RULES
 *   stage 2  document planning      order and grouping               plan()
 *   stage 3  microplanning          aggregation, lexical choice      in-rule
 *   stage 4  surface realisation    plurals, lists, agreement        helpers
 *
 * THE RULE, in full:
 *
 *   The narrator may state what the engine stated, and may state how many
 *   times the engine stated it. It may not derive a new quantity from the
 *   values in the rows.
 *
 * So COUNT(*) is allowed, because that is a property of the query. AVG(kg) is
 * not, because that is a health judgment, and health judgments belong to the
 * engine where they can be tested. Where the engine has already produced text
 * - gates.escalation, verdicts.reason - it is quoted verbatim and never
 * paraphrased, which is the discipline safety.py applies when it emits
 * hardcoded escalation strings rather than letting a model phrase them.
 *
 * Every message carries the SQL that produced it. The UI renders that as a
 * "show the rows" control which runs the query for real. A sentence you cannot
 * trace is a sentence this file is not allowed to emit.
 */
"use strict";

const Narrator = (() => {

  /* ---- stage 4: surface realisation ------------------------------------ */

  const plural = (n, one, many) => (n === 1 ? one : (many || one + "s"));

  // Counts read as prose, not as data. "2 goals are below the floor" is a
  // spreadsheet talking; a measured QUANTITY stays in digits, because "sixty
  // five thousand two hundred and ninety steps" helps nobody.
  const WORDS = ["zero", "one", "two", "three", "four", "five",
                 "six", "seven", "eight", "nine"];
  const count = (n) => (n >= 0 && n < WORDS.length && Number.isInteger(n))
    ? WORDS[n] : num(n);

  function listify(items) {
    if (items.length === 0) return "";
    if (items.length === 1) return items[0];
    return items.slice(0, -1).join(", ") + " and " + items[items.length - 1];
  }

  // Numbers are rendered, never recomputed. The dp argument chooses how much
  // of a stored value to show; it does not round anything into existence.
  const num = (x, dp = 0) =>
    (x === null || x === undefined) ? "" :
      Number(x).toLocaleString("en-GB", { maximumFractionDigits: dp,
                                          minimumFractionDigits: 0 });

  const esc = (s) => String(s).replace(/[&<>]/g,
    c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]));

  const quote = (s) => `<q>${esc(String(s).replace(/\s+/g, " ").trim())}</q>`;

  // A message begins a sentence. Rules interpolate a title or a column name at
  // position zero often enough that leaving this to each rule guarantees one
  // of them forgets.
  const cap = (s) => s.replace(/^(<[^>]+>)*[a-z]/,
    m => m.slice(0, -1) + m.slice(-1).toUpperCase());

  /* ---- two kinds of number ----------------------------------------------
   *
   * Every figure on this page came out of a table, but they did not all get
   * there the same way, and the difference is the most important thing about
   * them:
   *
   *   RECORDED  a value that entered the record from a source. A scale said
   *             75.9, the athlete declared a target of 30, a watch reported
   *             142 bpm. Someone or something observed it.
   *
   *   DERIVED   a value computed from other values. 44.6 per cent is not a
   *             thing anybody measured; it is arithmetic over a target and a
   *             count. So is `counted`, so is every COUNT(*) in this file.
   *
   * They are set in different ink because a reader who cannot tell them apart
   * will grant a derivation the standing of an observation, and derivations
   * inherit every assumption in their inputs. This is the typographic form of
   * the rule the whole client runs on.
   *
   * COUNTS FROM THIS FILE ARE MARKED DERIVED, including the ones the rule
   * permits. "The narrator may state how many times the engine stated it"
   * makes counting legal; it does not make a count an observation.
   *
   * Units take the same colour unbolded, and use the symbol where one exists -
   * the number is the figure, the unit is a label on it, and bolding both
   * gives the unit a weight it has not earned. */

  const UNIT = {
    distance_km: "km", steps: "steps", active_min: "min",
    kg: "kg", kcal_in: "kcal", kcal_out: "kcal", protein_g: "g",
    sleep_h: "h", rhr: "bpm", avg_hr: "bpm", duration_s: "s",
    external: null,
  };
  const PERIOD = { weekly: "a week", daily: "a day", monthly: "a month" };

  // A unit that is a symbol binds to its number; a word does not. "45%" and
  // "13.38 km" are both right and the rule is typographic, not arbitrary.
  const BINDS = new Set(["%"]);

  function figure(value, kind, unit, dp = 0) {
    const u = unit === undefined || unit === null ? "" : String(unit);
    const sep = (!u || BINDS.has(u)) ? "" : " ";
    return `<b class="n n-${kind}">${num(value, dp)}</b>` +
           (u ? `${sep}<span class="u u-${kind}">${esc(u)}</span>` : "");
  }
  /* A THIRD channel, and deliberately not a third colour.
   *
   * Colour answers "where did this number come from". This answers a different
   * question - "how much does it claim" - and stacking a second question onto
   * the same channel is how a legible page becomes a cacophony. So it is a
   * dotted underline, and it composes with either colour.
   *
   * It marks the one class of number that is invisible in prose: a magnitude
   * the engine will not vouch for. 2.8 km off a crosstrainer console looks
   * exactly like 2.8 km measured, and `modelled` is the record saying it is
   * not. Ordinal quantities are the same claim - the engine vouches for the
   * ORDER and not the size - so they share the mark rather than earning
   * another one.
   *
   * The reason is in the title attribute, because a mark without a reason is
   * decoration a reader has to guess at. */
  const soft = (html, why) =>
    `<span class="soft" title="${esc(why)}">${html}</span>`;

  const rec = (v, unit, dp) => figure(v, "recorded", unit, dp);
  const der = (v, unit, dp) => figure(v, "derived", unit, dp);
  const pct = (v) => figure(v, "derived", "%", 0);

  // A spelled count is still a derived count, and carries the same ink. The
  // alternative - words plain, digits coloured - would make the marking look
  // like a style choice rather than a claim about where a number came from.
  const derCount = (n) => `<b class="n n-derived">${count(n)}</b>`;

  // "13.38 of 30 km a week". `counted` is DERIVED (the engine aggregated it);
  // `target` is RECORDED (the athlete declared it). They sit next to each
  // other in one phrase and are not the same kind of fact.
  function quantity(counted, target, metric, period) {
    const unit = UNIT[metric] !== undefined ? UNIT[metric] : metric;
    const per = PERIOD[period] || "";
    const head = (counted === null || counted === undefined)
      ? `a target of ${rec(target, unit, 2)}`
      : `${der(counted, null, 2)} of ${rec(target, unit, 2)}`;
    return per ? `${head} ${per}` : head;
  }

  /* ---- stage 1: content determination ---------------------------------- */
  /* Each rule returns zero or more messages. A rule that finds nothing worth
   * saying says nothing: silence is a valid and common output, and a rule that
   * always produces a sentence is a rule that is padding.                   */

  const RULES = [];
  const rule = (id, section, priority, run) =>
    RULES.push({ id, section, priority, run });

  /* An open gate outranks everything. The engine wrote the escalation text;
   * it is reproduced without editing. G68: safety fires unconfigured.       */
  rule("open-gate", "now", 0, (q) => {
    const sql = "SELECT date, slug, restricts, reason, severity, status, " +
                "precondition, escalation FROM gates WHERE status <> 'cleared'";
    return q(sql).map(g => {
      // `reason` already ends with the check and its status, which the next
      // clause states properly. Repeating it reads as a stutter.
      const why = String(g.reason).replace(/\s*-\s*check\s+'[^']*':.*$/, "");
      return {
        tone: "stop",
        text: `<strong>${esc(g.restricts)} work is gated.</strong> ` +
              `The engine recorded ${quote(why)}, severity ` +
              `<code>${esc(g.severity)}</code>, and set one condition: ` +
              `<code>${esc(g.precondition)}</code>, currently ` +
              `<code>${esc(g.status)}</code>. ` +
              `Its words, not mine: ${quote(g.escalation)}`,
        sql,
      };
    });
  });

  /* Goals below a floor. Aggregated into one sentence (stage 3) because three
   * separate sentences of the same shape read as three separate problems.   */
  rule("goal-breach", "goals", 10, (q) => {
    const sql = "SELECT slug, title, polarity, metric, period, progress_pct, " +
                "counted, target, breach FROM goal_progress " +
                "WHERE breach IS NOT NULL ORDER BY progress_pct";
    const rs = q(sql);
    if (!rs.length) return [];
    const parts = rs.map(r =>
      `<em>${esc(r.title)}</em> (${quantity(r.counted, r.target, r.metric, r.period)}, ` +
      `${pct(r.progress_pct)})`);
    return [{
      tone: "watch",
      text: `${rs.length === 1 ? "One goal is" : derCount(rs.length) + " goals are"} ` +
            `below the ${rs[0].polarity === "floor" ? "floor" : "line"} you set: ` +
            listify(parts) + ". " +
            "That is the engine's arithmetic against the target you declared, " +
            "not a judgment about the week.",
      sql,
    }];
  });

  /* The other side of the same table, and it has to be said in the same
   * breath, or the narrator only ever reports deficits - which is a way of
   * lying by selection while every individual sentence stays true.          */
  rule("goal-holding", "goals", 11, (q) => {
    const sql = "SELECT slug, title, metric, period, achievement_status, " +
                "lifecycle_status, progress_pct, counted, target " +
                "FROM goal_progress WHERE achievement_status = 'sustaining'";
    const rs = q(sql);
    return rs.map(r => ({
      tone: "good",
      text: `<em>${esc(r.title)}</em> is marked <code>sustaining</code>: ` +
            `${quantity(r.counted, r.target, r.metric, r.period)}. ` +
            `The engine closed this one and is still counting it.`,
      sql,
    }));
  });

  /* G83: what someone would be sad to lose is never a number. A goal with no
   * target is not an incomplete goal, and the narrator must not treat it as
   * an omission to be chased.
   *
   * Split by `verification`, because "has no target" fuses two unrelated
   * things and this project does not fuse axes. A goal verified by ATTESTATION
   * has no number because none would mean anything; a goal verified
   * EXTERNALLY has a perfectly good number that lives somewhere this engine
   * cannot see. Reporting them in one sentence would imply the second is as
   * unmeasurable as the first, which is false and would read as this tool
   * declining to look.                                                       */
  rule("goal-attested", "goals", 12, (q) => {
    const sql = "SELECT slug, title, motivator FROM goal_progress " +
                "WHERE target IS NULL AND verification = 'attested'";
    const rs = q(sql);
    if (!rs.length) return [];
    return [{
      tone: "note",
      text: `${derCount(rs.length)} of your goals ${plural(rs.length, "carries", "carry")} ` +
            `no number and ${plural(rs.length, "is", "are")} true only when you ` +
            `say so: ` + listify(rs.map(r => `<em>${esc(r.title)}</em>`)) + ". " +
            "Nothing here can score " + plural(rs.length, "it", "them") + ", and " +
            "that is not a gap in the record. Some of what a person is training " +
            "for does not reduce to a quantity, and a tool that only recognises " +
            "the measurable ones will quietly talk you out of the rest.",
      sql,
    }];
  });

  rule("goal-external", "goals", 12.5, (q) => {
    const sql = "SELECT slug, title, tracker, event FROM goal_progress " +
                "WHERE target IS NULL AND verification = 'external'";
    const rs = q(sql);
    if (!rs.length) return [];
    const parts = rs.map(r => `<em>${esc(r.title)}</em>` +
      (r.tracker ? ` (${esc(r.tracker)})` : ""));
    return [{
      tone: "note",
      text: `${derCount(rs.length)} ${plural(rs.length, "goal is", "goals are")} ` +
            `settled somewhere this engine cannot see: ` + listify(parts) + ". " +
            `There is a number, and it is not in here. The engine tracks ` +
            plural(rs.length, "it", "them") + ` without pretending to measure ` +
            plural(rs.length, "it", "them") + `, which is the honest position ` +
            `for a tool holding only its own record.`,
      sql,
    }];
  });

  /* A hard deadline that has passed on a goal nobody has closed. Stated as a
   * fact about the record, with no verdict attached: the engine has not
   * decided this goal failed, and neither has the athlete, and it is not the
   * narrator's business to break the tie.                                    */
  rule("deadline-passed", "goals", 14, (q) => {
    const sql = "SELECT slug, title, deadline, deadline_kind, days_to_deadline, " +
                "lifecycle_status, verification FROM goal_progress " +
                "WHERE days_to_deadline < 0 AND lifecycle_status = 'active'";
    const rs = q(sql);
    return rs.map(r => ({
      tone: "watch",
      text: `<em>${esc(r.title)}</em> passed its ` +
            `${r.deadline_kind === "hard" ? "hard " : ""}deadline of ` +
            `${esc(r.deadline)}, ${der(Math.abs(r.days_to_deadline), "days")} ago, ` +
            `and is still open. ` +
            (r.verification === "external"
              ? "Nothing has arrived to settle it, which is what a goal held " +
                "outside the record looks like when the result never comes back in."
              : "The engine has not marked it missed and will not do so on its own."),
      sql,
    }));
  });

  /* ---- the journey ------------------------------------------------------
   * A plan is not a static thing that gets graded, it is a thing the athlete
   * keeps rewriting, and the rewrites carry more about the arc than any of
   * the numbers do. The engine records every edit with the reason given at
   * the time, so the narrator can tell that part of the story in the
   * athlete's own words rather than characterising it in its own.          */

  const CHURN = "SELECT date, slug, kind, metric, edit_no, before, after, " +
                "direction, deadline_pushed, deadline_kind, reason, set_by, " +
                "suspicious, unexplained FROM plan_churn";

  rule("plan-churn", "journey", 15, (q) => {
    const sql = CHURN + " ORDER BY date";
    const rs = q(sql);
    if (!rs.length) return [];
    /* A chronology, one edit per line. Run together as a comma list these
     * became unreadable, because each item already contains commas of its
     * own - and a sequence of decisions a person made over three months is
     * not a list of items, it is an order of events. */
    const lines = rs.map(r => {
      const what = r.kind === "threshold"
        ? `the <code>${esc(r.slug)}</code> threshold`
        : `<em>${esc(r.slug)}</em>`;
      // Only state a movement the row actually records. `before` equal to
      // `after` with a pushed deadline is a real and different edit: the
      // target held and the date moved, and calling that a change to the
      // target would be the narrator inventing the more dramatic version.
      const moved = (r.before !== null && r.after !== null && r.before !== r.after)
        ? `${esc(r.direction)} from ${rec(r.before)} to ${rec(r.after)}`
        : (r.deadline_pushed
            ? `kept its target and moved its ${r.deadline_kind === "hard" ? "hard " : ""}deadline`
            : esc(r.direction));
      const why = r.reason ? `: ${quote(r.reason)}` : "";
      return `<span class="when">${esc(r.date)}</span> ${what} ${moved}${why}`;
    });
    return [{
      tone: "note",
      text: `The plan moved ${derCount(rs.length)} ${plural(rs.length, "time")}, ` +
            `and the record kept the reason each time.` +
            `<span class="chron">` + lines.join("<br>") + `</span><br>` +
            `None of that is drift. A plan edited with a reason attached is a ` +
            `plan being used, and the engine keeps the reasons so that the ` +
            `edits stay legible as decisions rather than accumulating as noise.`,
      sql,
    }];
  });

  /* The engine flags an edit it finds suspicious. That flag is reported, and
   * it is reported as a flag: the engine is a piece of software applying a
   * rule about loosened thresholds, it does not know about the travel week,
   * and a narrator that repeats a machine's suspicion as if it were a finding
   * about the person has done something worse than say nothing.            */
  rule("churn-flagged", "journey", 16, (q) => {
    const sql = CHURN + " WHERE suspicious = 1";
    const rs = q(sql);
    return rs.map(r => ({
      tone: "watch",
      text: `The engine flagged one of those edits: ` +
            `<code>${esc(r.slug)}</code> was ${esc(r.direction)}` +
            (r.before !== null && r.after !== null
              ? ` from ${rec(r.before)} to ${rec(r.after)}` : "") +
            ` on ${esc(r.date)}. It flags a loosened threshold on principle, ` +
            `and it is a flag rather than an accusation. ` +
            (r.reason
              ? `The reason you gave at the time is in the record: ${quote(r.reason)}. `
              : `No reason is recorded against it. `) +
            (r.unexplained === 0
              ? `The engine marks it explained and is not asking again.`
              : `The engine still has it down as unexplained.`),
      sql,
    }));
  });

  /* Something that happened and was not in any plan. Reported without being
   * folded into progress, because an achievement the athlete did not budget
   * for is not evidence about a target they set for something else.        */
  rule("achievements", "journey", 17, (q) => {
    const sql = "SELECT date, title, goal, source, note, occurred_date " +
                "FROM achievements ORDER BY date";
    const rs = q(sql);
    return rs.map(r => ({
      tone: "good",
      text: `<strong>${esc(r.title)}</strong>, recorded ${esc(r.date)}` +
            (r.goal ? ` against the <em>${esc(r.goal)}</em> goal` : "") + ". " +
            (r.note ? `Your note: ${quote(r.note)}. ` : "") +
            `The engine keeps it as its own fact and does not quietly count it ` +
            `towards a target it was never part of.`,
      sql,
    }));
  });

  /* Two sources disagreed. The independence split is the whole point and the
   * distinction was learned the hard way on this project: two transcriptions
   * of one instrument agreeing tells you the transcription was faithful, and
   * tells you nothing whatever about the measurement.                       */
  rule("conflicts", "resolution", 20, (q) => {
    const sql = "SELECT date, dataset, field, chosen_source, chosen_value, " +
                "over_source, over_value, independent, reason FROM resolution " +
                "WHERE disagreed = 1 ORDER BY date";
    const rs = q(sql);
    if (!rs.length) return [];
    const indep = rs.filter(r => r.independent).length;
    const fields = [...new Set(rs.map(r => r.field))];
    let text =
      `Two sources disagreed ${derCount(rs.length)} ${plural(rs.length, "time")}, ` +
      `over ${listify(fields.map(f => `<code>${esc(f)}</code>`))}. ` +
      `The engine picked a winner each time and kept the loser.`;
    if (indep !== rs.length) {
      text += ` ${cap(derCount(rs.length - indep))} of those ` +
        `${plural(rs.length - indep, "was", "were")} between sources the engine ` +
        `does not consider independent, which is a weaker thing than it looks: ` +
        `when one instrument reaches the record by two paths, agreement checks ` +
        `the copying and not the measurement.`;
    }
    return [{ tone: "note", text, sql }];
  });

  /* Sits under the weight chart, which now draws each weigh-in by its origin.
   * The chart shows the pattern; this says what the pattern is, because a
   * reader who has not been told what a hollow ring means will read it as a
   * style choice.                                                          */
  rule("weight-origin", "weight", 30, (q) => {
    const sql = "SELECT origin, COUNT(*) AS n, SUM(COUNT(*)) OVER () AS total " +
                "FROM weight WHERE kg IS NOT NULL GROUP BY origin ORDER BY n DESC";
    const rs = q(sql);
    if (!rs.length) return [];
    const unknown = rs.find(r => r.origin === null);
    const named = rs.filter(r => r.origin !== null);
    if (!unknown) {
      return [{
        tone: "note",
        text: `Every one of the ${der(rs[0].total)} weigh-ins above names where ` +
              `it came from: ` +
              listify(named.map(r => `<code>${esc(r.origin)}</code> ${der(r.n)}`)) + ".",
        sql,
      }];
    }
    return [{
      tone: "note",
      text: `Of the ${der(unknown.total)} weigh-ins above, ${der(unknown.n)} name ` +
            `no origin at all. The rest name one: ` +
            listify(named.map(r => `<code>${esc(r.origin)}</code> ${der(r.n)}`)) + ". " +
            `The hollow rings are the ones whose custody was never written down. ` +
            `They are not wrong and they are not guesses; nobody recorded how ` +
            `they reached the record, and that cannot be recovered later. ` +
            `Drawing them as solid dots would have been this page vouching for ` +
            `something the record does not.`,
      sql,
    }];
  });

  /* Contract 47. Round-number and personal-first crossings of the weight
   * series: goal-independent and history-wide, which makes this the only
   * progress surface on the page that says anything on a record with no goal
   * declared. Everything else here is scored against something the athlete
   * stated, so a record stating nothing gets silence.
   *
   * TWO KINDS, TWO SENTENCES, and that is the whole of this rule. Both kinds
   * carry their evidence under the same two column names, and the names mean
   * different things:
   *
   *   personal_first  previous_value/previous_date is the record this reading
   *                   BEAT.
   *   round_number    previous_value/previous_date is the last reading ALREADY
   *                   ON THE SIDE just arrived at - which can be months old and
   *                   NUMERICALLY FURTHER from the level than the reading taken
   *                   immediately before the crossing.
   *
   * Rendered through one template the round number reads as its own opposite.
   * The demo holds the case exactly: on 2030-04-13 the series crossed BELOW 80
   * with a previous_value of 79.4, so "down to 80 (was 79.4)" would print a
   * downward crossing as a six-hundred-gram gain. The engine shipped that
   * defect once and corrected it, and its CLI wording is what is matched here
   * rather than a second vocabulary invented for one fact.
   *
   * So the round-number sentence names a DATE and never a former weight, and
   * tools/test_narrator.js asserts it against both the demo and a synthetic
   * row. A null previous_date is the STRONGER claim rather than a missing
   * value - the level was never reached from that side before - and gets its
   * own sentence instead of a "since null" or a silence.                     */
  /* THE KINDS THIS PAGE HAS BEEN TAUGHT, as an allowlist rather than a set of
   * things to exclude. A denylist would have to be updated by whoever adds the
   * next kind to the ENGINE, in a repo they are not editing, which is not a
   * control at all. This way an unrecognised kind refuses by default and the
   * omission is loud. */
  const KNOWN_CROSSING_KINDS = new Set(
    ["round_number", "personal_first", "band"]);

  rule("crossings", "weight", 31, (q) => {
    const sql = "SELECT date, kind, metric, value, direction, " +
                "previous_value, previous_date FROM crossings " +
                "ORDER BY date DESC, kind";
    const rs = q(sql);
    /* Absence is absence. A record with fewer than two weight readings has no
     * crossings, and an empty box under this chart would read as a failure to
     * look rather than as nothing having happened.                           */
    if (!rs.length) return [];
    const lines = rs.map(r => {
      const side = r.direction === "down" ? "below" : "above";
      let said;
      if (r.kind === "round_number" || r.kind === "band") {
        /* ONE SENTENCE FOR TWO KINDS, and it is the engine's own choice
         * rather than a shortcut taken here: `crossings._last_on_destination_
         * side` backs the evidence pair on both, so the pair means exactly the
         * same thing, and `cli.py` renders them through one branch for that
         * reason. A second copy would drift from the first.
         *
         * `value` on both is a LEVEL, not a reading anybody took - a rung on
         * the ladder for `round_number`, a boundary for `band` - so it takes
         * the derived ink. Teal would say a scale reported it, and none did.
         *
         * A BAND VALUE IS A NUMBER AND NEVER A NAME. The engine may compute
         * the ratio and state the boundary as a boundary; it may never name
         * the band, and that ruling binds this client too. The template holds
         * `metric` and two figures and has nowhere a category word could sit -
         * see docs/medical-boundary.md, where a bound stated as a bound is
         * class (a) and a category is class (c). tools/test_narrator.js scans
         * the whole rendered output for one. */
        const level = der(r.value, null, 2);
        said = r.previous_date === null
          ? `${esc(r.metric)} ${side} ${level} for the first time in this record`
          : `first ${esc(r.metric)} ${side} ${level} since ${esc(r.previous_date)}`;
      } else if (r.kind === "personal_first") {
        /* Here `value` IS the reading, and so is the extreme it beat. Both are
         * observations and both are recorded ink. */
        const arrow = r.direction === "down" ? "low" : "high";
        const was = r.previous_date === null ? ""
          : `, beating ${rec(r.previous_value, null, 2)} on ${esc(r.previous_date)}`;
        said = `${esc(r.metric)} ${arrow} of ${rec(r.value, null, 2)}${was}`;
      } else {
        /* AN UNKNOWN KIND REFUSES, and this branch is the durable half of the
         * feature.
         *
         * This rule shipped with `round_number` tested and everything else
         * falling through to the personal-first sentence. Contract 48 then
         * added `band`, and that fall-through would have rendered a boundary
         * as "a low of 30, beating 25" - a sentence about the athlete's body
         * that no row asserts. Dropping the row would have been better and is
         * still not good; #387's own changelog names silent dropping as the
         * defect it found elsewhere.
         *
         * So the branches are an ALLOWLIST and the default refuses. Contract
         * 49 may add a fifth kind, and when it does this page will say it
         * cannot describe that row rather than describing it as something it
         * is not. A client that guesses which sentence fits an unfamiliar row
         * is how a record ends up asserting what nobody recorded. */
        said = `this page has no sentence for this kind of crossing, and ` +
               `will not borrow one written for another`;
      }
      /* The kind is printed on every line under the engine's own name. A
       * reader scanning the list cannot otherwise tell an all-time extreme
       * from a threshold that can be re-crossed next week, and the kinds sit
       * interleaved by date. */
      return `<span class="when">${esc(r.date)}</span> ` +
             `<code>${esc(r.kind)}</code> ${said}`;
    });
    const strange = [...new Set(rs.filter(r => !KNOWN_CROSSING_KINDS.has(r.kind))
                                  .map(r => r.kind))];
    const out = [{
      tone: "note",
      text: `The engine marks ${derCount(rs.length)} ` +
            `${plural(rs.length, "crossing")} read from this series, newest ` +
            `first.` +
            `<span class="chron">` + lines.join("<br>") + `</span><br>` +
            `None of these needs a goal. Every other progress figure on this ` +
            `page is scored against something you declared, so a record that ` +
            `declared nothing gets silence; a crossing is true or false of the ` +
            `series alone. The kinds are not interchangeable and they carry ` +
            `their evidence under the same column names: a ` +
            `<code>personal_first</code> names the reading it beat, while a ` +
            `<code>round_number</code> and a <code>band</code> each name the ` +
            `last time the series was on the side it has just arrived at. ` +
            `That earlier reading can be older, and further from the level, ` +
            `than the one taken just before the crossing - so those two are ` +
            `given as a date and never as a former weight. ` +
            /* Class (a) then class (b), and nothing else is available here.
             * The record holds the boundary and holds no name for it, so the
             * only honest closing move is to say the page stops there. Saying
             * nothing at all would leave the reader to supply the missing
             * word themselves, which is the failure this is guarding. */
            `A <code>band</code> names a population-reference boundary the ` +
            `series crossed: its value is the boundary itself and never your ` +
            `own ratio on that date. The record carries no name for that ` +
            `boundary, and neither will this page.`,
      sql,
    }];
    if (strange.length) {
      /* NO NUMBER IN THIS SENTENCE, deliberately. A total across several
       * unknown kinds is a sum the cited rows do not contain - the grounding
       * test grounds each kind's own tally, not their sum - so counting them
       * would be this file deriving a quantity to complain about deriving
       * quantities. The kinds are named instead, which is the useful part. */
      out.push({
        tone: "watch",
        text: `${plural(strange.length, "One kind", "Some kinds")} of ` +
              `crossing in this record ${plural(strange.length, "is", "are")} ` +
              `unknown to this page: ` +
              listify(strange.map(k => `<code>${esc(k)}</code>`)) + ". " +
              `${plural(strange.length, "Its rows are", "Their rows are")} ` +
              `listed above and left undescribed rather than ` +
              `rendered through a sentence written for another kind. The ` +
              `engine has moved and this client has not caught up yet, which ` +
              `is the signal this repo exists to give rather than a fault in ` +
              `the record.`,
        sql,
      });
    }
    return out;
  });

  /* Where the numbers came from. 162 of 193 rows arriving by unknown transit
   * is the single most honest thing this database has to say about itself.  */
  rule("provenance", "record", 21, (q) => {
    // The total is asked of the database rather than summed from the group
    // counts here. Adding them up would be a new quantity computed in the
    // client, which is the one thing this file may not do, and the grounding
    // test caught it doing precisely that.
    const sql = "SELECT trust, COUNT(*) AS n, SUM(COUNT(*)) OVER () AS total " +
                "FROM provenance GROUP BY trust ORDER BY n DESC";
    const rs = q(sql);
    if (!rs.length) return [];
    const total = rs[0].total;
    const top = rs[0];
    const parts = rs.map(r => `<code>${esc(r.trust)}</code> ${der(r.n)}`);
    let text = `Provenance across ${der(total, "record-days")}: ` +
               listify(parts) + ".";
    if (top.trust === "unknown-transit") {
      text += " The largest group is the one where the number arrived and the " +
              "path it took did not. Those values are not wrong; it is their " +
              "custody that is unrecorded, and no amount of charting will " +
              "recover it after the fact.";
    }
    return [{ tone: "note", text, sql }];
  });

  /* G82: the unaccounted period. State that it exists, never ask why. The
   * days a person stops logging are frequently the days worth knowing about,
   * and a tool that demands an explanation is a tool they will stop opening. */
  rule("unlogged", "coverage", 22, (q) => {
    // One query, not three. The two side queries this used to run produced
    // numbers the "show the rows" control would not have shown, which is the
    // same defect as inventing them.
    const sql = "SELECT COUNT(*) AS logged, MIN(date) AS a, MAX(date) AS b, " +
                "SUM(CASE WHEN coverage IS NULL THEN 1 ELSE 0 END) AS blank, " +
                "SUM(CASE WHEN coverage = 'partial' THEN 1 ELSE 0 END) AS partial " +
                "FROM daily";
    const r = q(sql)[0];
    if (!r || !r.logged) return [];
    const partial = { n: r.partial }, blank = { n: r.blank };
    let text = `The record runs ${esc(r.a)} to ${esc(r.b)}, ` +
               `${der(r.logged, "days")}.`;
    if (blank && blank.n) {
      text += ` ${cap(derCount(blank.n))} of them carry no coverage marking at all, ` +
              `which the engine keeps distinct from a day marked empty. ` +
              `Unannotated is not the same as nothing happened.`;
    }
    if (partial && partial.n) {
      text += ` ${cap(derCount(partial.n))} ${plural(partial.n, "is", "are")} marked <code>partial</code>.`;
    }
    return [{ tone: "note", text, sql }];
  });

  /* Weekly verdicts, counted by outcome. no_data is reported as its own
   * category and never folded into a miss: not measuring is not failing.    */
  rule("verdicts", "attainment", 23, (q) => {
    const sql = "SELECT verdict, COUNT(*) AS n, SUM(COUNT(*)) OVER () AS total " +
                "FROM verdicts GROUP BY verdict ORDER BY n DESC";
    const rs = q(sql);
    if (!rs.length) return [];
    const by = Object.fromEntries(rs.map(r => [r.verdict, r.n]));
    const total = rs[0].total;
    let text = `Across ${der(total, "weekly checks")} the engine returned ` +
               listify(rs.map(r => `<code>${esc(r.verdict)}</code> ${der(r.n)}`)) + ".";
    if (by.no_data) {
      text += ` The ${derCount(by.no_data)} <code>no_data</code> ` +
              `${plural(by.no_data, "week")} ${plural(by.no_data, "is", "are")} ` +
              `not ${plural(by.no_data, "a miss", "misses")}. ` +
              `The engine declines to score a week it cannot see, and refusing ` +
              `to guess is the behaviour, not a shortcoming of it.`;
    }
    return [{ tone: "note", text, sql }];
  });

  /* Claims that were merged. The record changing its mind is a feature and
   * ought to be visible rather than quietly resolved behind the read model. */
  rule("merged", "record", 24, (q) => {
    const sql = "SELECT claim_id, dataset, date, source, merged_into " +
                "FROM claims WHERE merged_into IS NOT NULL";
    const rs = q(sql);
    if (!rs.length) return [];
    return [{
      tone: "note",
      text: `${cap(derCount(rs.length))} ${plural(rs.length, "claim")} ` +
            `${plural(rs.length, "was", "were")} each superseded by a later one. ` +
            `The originals are still in the log; the read model shows what won, ` +
            `and the log shows that anything was ever in question.`,
      sql,
    }];
  });

  /* Milestones under a target that has since moved. This is G25 made visible:
   * old rows keep validating, so the history of a goal survives its edit.   */
  rule("milestone-history", "goals", 13, (q) => {
    const sql = "SELECT label, COUNT(*) AS n FROM milestones " +
                "GROUP BY label ORDER BY n DESC";
    const rs = q(sql);
    if (rs.length < 2) return [];
    const targets = new Set();
    for (const r of rs) {
      const m = /of (.+)$/.exec(r.label);
      if (m) targets.add(m[1]);
    }
    const steps = [...targets].filter(t => /\d/.test(t));
    if (steps.length < 2) return [];
    return [{
      tone: "note",
      text: `The milestone log names more than one version of the same goal ` +
            `(${listify([...targets].slice(0, 3).map(t => `<em>${esc(t)}</em>`))}` +
            `${targets.size > 3 ? ", and others" : ""}). ` +
            `A goal that was edited did not erase what was true under the old ` +
            `one. Progress recorded against a target you have since raised is ` +
            `still progress that happened.`,
      sql,
    }];
  });

  /* ---- stage 2: document planning -------------------------------------- */

  /* Sections carry a MOUNT: where on the page they belong.
   *
   * The brief leads with the plan and the arc through it, because that is the
   * thing a person came to find out. What follows it used to be five more
   * paragraphs about measurement, sitting hundreds of pixels above the charts
   * they described - so a sentence about unlogged days and the heatmap that
   * shows them were never on screen together, and the reader had to hold one
   * in their head while scrolling to the other. Those now sit under their own
   * chart, where the sentence and the picture are one thing.
   *
   * What stays at the bottom is record-wide: it belongs to no single chart,
   * so putting it under one would imply a scope it does not have.
   *
   * The gate keeps the top. It is not a measurement narrative and not part of
   * the arc: it is a restriction that is live right now, and a health tool
   * that renders a safety gate below a goal summary has got its priorities
   * from a layout grid.                                                     */
  const SECTIONS = [
    { id: "now",        mount: "brief",    title: "What needs attention" },
    { id: "goals",      mount: "brief",    title: "Against what you said you wanted" },
    { id: "journey",    mount: "brief",    title: "How the plan moved, and why" },
    { id: "weight",     mount: "c-weight", title: null },
    { id: "coverage",   mount: "c-heat",   title: null },
    { id: "attainment", mount: "c-verd",   title: null },
    { id: "resolution", mount: "c-resolution", title: null },
    { id: "record",     mount: "record",   title: "What the record knows about itself" },
  ];

  /* Returns mount id -> sections, so the page places each group without
   * needing to know which rule produced what. */
  function plan(messages) {
    const mounts = {};
    for (const s of SECTIONS) {
      const mine = messages.filter(m => m.section === s.id)
                           .sort((a, b) => a.priority - b.priority);
      if (!mine.length) continue;
      (mounts[s.mount] ||= []).push({ ...s, messages: mine });
    }
    return mounts;
  }

  /* ---- driver ----------------------------------------------------------- */

  function generate(query) {
    const messages = [];
    for (const r of RULES) {
      let produced;
      try {
        produced = r.run(query) || [];
      } catch (err) {
        /* A rule that throws is a broken rule, and the honest report of a
         * broken rule is not silence. Silence here would be a narrator that
         * shrinks as the schema drifts while continuing to look complete,
         * which is precisely the failure this client exists to refuse.     */
        produced = [{
          tone: "broken",
          text: `The rule <code>${esc(r.id)}</code> could not run against this ` +
                `database: <code>${esc(err && err.message || err)}</code>. ` +
                `Whatever it had to say is missing from what follows.`,
          sql: null,
        }];
      }
      for (const m of produced) {
        messages.push({ ...m, text: cap(m.text), rule: r.id,
                        section: r.section, priority: r.priority });
      }
    }
    return plan(messages);
  }

  return { generate, RULES, SECTIONS,
           _internal: { listify, plural, num, count, quantity, esc,
                        figure, rec, der, pct, derCount, soft, UNIT } };
})();

if (typeof module !== "undefined" && module.exports) module.exports = Narrator;
